pipeline {
    agent {
        dockerContainer { 
            image 'jenkins/inbound-agent:latest-jdk17'  
        }
    }
    stages {
        stage('Primer Stage') {
            steps {
                script {
                    sh """
                        echo Hello World!
                        echo Otro
                    """
                }
            }
        }
        stage('Segundo Stage') {
            steps {
                script {
                    sh """
                        echo Segunda parte
                    """
                }
            }
        }
    }
}
