pipeline {
    agent {
        label "jdk17"
    }
    environment {
        VERSION = '${BUILD_TAG}'
        DOCKER_HUB_REPOSITORY = 'quinont'
    }
    stages {
        stage('Revisando contenido') {
            steps {
                script {
                    sh """
                        ls -alF
                    """
                }
            }
        }
        stage('Build y push de la imagen') {
            steps {
                script {
                    withCredentials([file(credentialsId: 'docker-hub-credentials', variable: 'DOCKER_HUB_CREDENTIALS')]) {
                        sh """
                            whoami
                            cp ${DOCKER_HUB_CREDENTIALS} /kaniko/.docker/config.json 
                            /kaniko/executor --dockerfile ${WORKSPACE}/nginx-test/Dockerfile --destination=${DOCKER_HUB_REPOSITORY}/nginx-test:${VERSION} --context=${WORKSPACE}/nginx-test/
                        """
                    }
                }
            }
        }
    }
}
